M48
; DRILL file {KiCad (6.0.8-1)-1} date Sunday, October 23, 2022 at 11:26:31 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-23T23:26:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X2.8449Y-3.2462
X2.8449Y-3.4738
T2
X2.955Y-3.755
X3.155Y-3.715
X3.155Y-3.795
T0
M30
